from recommonmark.transform import AutoStructify
import warnings

# -- Server configuration -----------------------------------------------------

SERVER_URL = "http://localhost:8000"


# -- General configuration ----------------------------------------------------

# Add any Sphinx extension module names here, as strings
extensions = [

]

# The suffixes of source names
source_suffix = ['.rst', '.md']

# The master toctree document
master_doc = 'index'

# General information about the project
project = "Imoogi"
author = "Evgeny Dmitriev"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'README.md']

# The name of Pygments (syntax highlighting) style to use
pygments_style = 'sphinx'

# -- Options for not found extension ------------------------------------------

# Template used to render the HTML pages generated by this extension
notfound_template = "404.html"

# -- Option for HTML output ---------------------------------------------------

# The html theme to use for pages
html_theme = "pydata_sphinx_theme"

# Path to static file of the HTML documentation
html_static_path = ['_static']

# Path to templates of the HTML documentation
html_file_suffix = ".html"

# HTML title of the HTML documentation
html_title = "Imoogi"

# HTML short title of the HTML documentation
html_short_title = "Imoogi"

# Theme options are theme-specific and customize the look and feel of a theme
# further. For a list of options available for each theme, see the
# documentation.
# html_theme_options = {
#     "show_prev_next": False,

#     "navbar_end": ["theme-switcher", "version-switcher"],
#     # "page_sidebar_items": "page-toc.html",
# }

# Last updated format
html_last_updated_fmt = "%b %d, %Y"

# URL which points to the root of the HTML documentation
html_baseurl = SERVER_URL

# Dictionary of values to pass into the template engine’s context for all pages
html_context = {"html_baseurl": html_baseurl}


# -- Initialize Sphinx --------------------------------------------------------

def setup(sphinx):
    warnings.filterwarnings(
        action="ignore",
        category=UserWarning,
        message=r".*Container node skipped.*",
    )
    sphinx.add_config_value("recommonmark_config", {
                            'enable_eval_rst': True}, True)
    sphinx.add_transform(AutoStructify)

